# Custom aliases performed on $(date) by debianFreshInstall.sh script.
alias ll='ls -lah'
alias rm='rm -vi'
alias cp='cp -vi'
alias mv='mv -vi'
alias agin='sudo apt get install'
alias agud='sudo apt get update'
alias agug='sudo apt get upgrade -y'
alias asea='apt search'

# Docker aliases
alias dpsa='docker ps -a'
alias drmi='docker rmi'
alias drmv='docker rm'
alias dpur='docker purge'
alias drun='docker run'
alias dpul='docker pull'
alias dpsh='docker push'
alias dlin='docker login'
alias dimg='docker image'
